<?php

/**
 * PluginUserTimezoneTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework.
 */
class PluginUserTimezoneTable extends Doctrine_Table
{

  /**
   * Returns an instance of this class.
   *
   * @return PluginUserTimezoneTable object
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('PluginUserTimezone');
  }
}
