<?php

/**
 * PluginUserTimezone.
 *
 * This class has been auto-generated by the Doctrine ORM Framework.
 *
 * @package    Jagmort
 * @subpackage Timezone
 * @author     Alexander Pervakov <frost.nzcr4@jagmort.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginUserTimezone extends BaseUserTimezone
{
}
